export const DEFAULT_REDACT_PATHS: string[] = [
  "password",
  "*.password",
  "*.*.password",
  "token",
  "*.token",
  "*.*.token",
  "[*].token",
  "apiKey",
  "*.apiKey",
  "*.*.apiKey",
  'headers["x-api-key"]',
  "headers['x-api-key']",
  "authorization",
  "*.authorization",
  "*.*.authorization",
  "headers.authorization",
  'headers["authorization"]',
  "headers['authorization']",
  "cookie",
  "*.cookie",
  "headers.cookie",
  "secret",
  "*.secret",
  "*.*.secret",
  "credentials.*",
];

export const CENSOR_VALUE = "[REDACTED]";
